name: Run Bright Books ETL

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1' 

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL Script
      env:
        DB_HOST: ${{ secrets.dbhost }}
        DB_PASSWORD: ${{ secrets.password }}
        GOOGLE_SA_KEY_JSON: ${{ secrets.google_key }} 
        DB_USER: "postgres"          
        DB_NAME: "postgres"          
        DB_PORT: "5432"              
        SHEET_ID: "15jf5Ys_DQOa0g56-Mjd6jzWzNke6O-Mg42cXXao5Mn8" # 👈 Remplace ce texte par ton vrai ID
        WORKSHEET: "Sheet1"        # Le nom exact de ton onglet Google Sheet
        TABLE_NAME: "pnl"
      run: |
        python etl.py